### ISSUE TITLE
Ensemble-related files can not download

### ISSUE THREAD

**Issue by ArcaneLex** [Nanasaki-Ai/HCMFN#1]
Ensemble-related files can not be download because the extract code is not provided.

**Comment by Nanasaki-Ai** [comment]
Thank you for your interest in our work.
Please use the link below to download.

Link：https://pan.baidu.com/s/1mY2BWLJqxprsQ4cZB2-SEw?pwd=4ecs 
code：4ecs

**Comment by ArcaneLex** [comment]
> Thank you for your interest in our work. Please use the link below to download.
> 
> Link：https://pan.baidu.com/s/1mY2BWLJqxprsQ4cZB2-SEw?pwd=4ecs code：4ecs

Thank you for your prompt reply.
